// src/server/prompts/categories/fallback/fallback-themes.ts
import type { WebsiteTheme } from '../../theme-types';

export const FALLBACK_THEMES: WebsiteTheme[] = [
  {
    id: 'modern-sidebar-fallback',
    name: 'Modern Sidebar',
    cssFile: 'modern-sidebar.css',
    category: 'fallback' as any,
    personality: 'Professional, clean, easy navigation with a sidebar.',
    fonts: { heading: 'Inter', body: 'Inter', googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;700&display=swap' },
    colors: { bg: '#ffffff', surface: '#f8fafc', primary: '#0f172a', secondary: '#3b82f6', text: '#1e293b', muted: '#64748b', border: '#e2e8f0' },
    layout: 'sidebar',
    animations: ['fadeUp'],
    jsFeatures: [],
    rtlSafe: true,
  },
  {
    id: 'minimal-centered-fallback',
    name: 'Minimal Centered',
    cssFile: 'minimal-centered.css',
    category: 'fallback' as any,
    personality: 'Clean, spacious, centered focus on content.',
    fonts: { heading: 'Outfit', body: 'Inter', googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600&family=Inter:wght@300;400;500&display=swap' },
    colors: { bg: '#fafafa', surface: '#ffffff', primary: '#171717', secondary: '#737373', text: '#262626', muted: '#a3a3a3', border: '#e5e5e5' },
    layout: 'centered',
    animations: ['fadeUp'],
    jsFeatures: [],
    rtlSafe: true,
  },
  {
    id: 'vibrant-grid-fallback',
    name: 'Vibrant Grid',
    cssFile: 'vibrant-grid.css',
    category: 'fallback' as any,
    personality: 'Energetic, card-based, modern and colorful.',
    fonts: { heading: 'Plus Jakarta Sans', body: 'Inter', googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;700&family=Inter:wght@300;400;500&display=swap' },
    colors: { bg: '#ffffff', surface: '#fefce8', primary: '#ca8a04', secondary: '#facc15', text: '#422006', muted: '#713f12', border: '#fef08a' },
    layout: 'grid-heavy',
    animations: ['fadeUp'],
    jsFeatures: [],
    rtlSafe: true,
  },
  {
    id: 'split-luxury-fallback',
    name: 'Split Luxury',
    cssFile: 'split-luxury.css',
    category: 'fallback' as any,
    personality: 'Elegant split-screen layout for a premium feel.',
    fonts: { heading: 'Cormorant Garamond', body: 'Inter', googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;700&family=Inter:wght@300;400;500&display=swap' },
    colors: { bg: '#fdfcfb', surface: '#ffffff', primary: '#44403c', secondary: '#78716c', text: '#1c1917', muted: '#57534e', border: '#e7e5e4' },
    layout: 'split-screen',
    animations: ['fadeUp'],
    jsFeatures: [],
    rtlSafe: true,
  },
];
