import type { Metadata } from "next";
import "./globals.css"; // Global styles for the application


export const metadata: Metadata = {
  title: "Create Next App", // Tab title for the application
  description: "Generated by create next app", // Description for SEO and social sharing
};


// The content of the page will be rendered here
export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
